### ISSUE TITLE
Druid metadata extractor

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#101]
Build a metadata extractor for druid.
Context: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1568825902061800?thread_ts=1568793997.052100&cid=CGFBVT23V

**Comment by jornh** [comment]
## Roadmap link

https://github.com/lyft/amundsen/blob/master/docs/roadmap.md#index-druid-tables-and-s3-buckets

**Comment by feng-tao** [comment]
We could leverage https://druid.apache.org/docs/latest/querying/sql.html#metadata-tables and use https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/extractor/sql_alchemy_extractor.py
