### ISSUE TITLE
no usage skews search results

### ISSUE THREAD

**Issue by javamonkey79** [lyft/amundsen#106]
Given - there is no usage data for any tables and you run a non field search
Then - result from elastic search will be incorrect as the field_value_factor modifier (log1p) will add 1 and take the natural log of 1, effectively making all scores 0

To fix this, we suggest using log2p instead.

**Comment by javamonkey79** [comment]
https://github.com/lyft/amundsensearchlibrary/pull/61

**Comment by feng-tao** [comment]
nice, I think the issue could be closed now given the pr is merged?
