### ISSUE TITLE
optimize docker images

### ISSUE THREAD

**Issue by jornh** [lyft/amundsen#109]
I would like to introduce a few optimizations of Docker images across the three service repos: 

* Reduce image size by switching to `python:3-slim` as base image, e.g. [Airflow](https://github.com/apache/airflow/blob/v1-10-stable/Dockerfile#L20) does this as well - this means even _quicker_ **Quickstart**
* Increase caching to speed up builds (mostly by eliminating pypi/npm dependency pulls and builds)
* Add Gunicorn similar to what's already introduced in https://github.com/lyft/amundsenmetadatalibrary/pull/66 to allow for a more production ready config (Werkzeug still possible if someone is using it)

This issue mostly to have a common place to link to for discussion etc.

**Comment by jornh** [comment]
According to https://hub.docker.com/r/amundsendev/amundsen-metadata/tags version 1.1.1 of metadata is 72 MB in compressed size. In comparison v1.0.19 was 347 MB.

This means only 1/4 download size for Amundsen Quickstart images.

**Comment by jornh** [comment]
According to https://hub.docker.com/r/amundsendev/amundsen-metadata/tags version 1.1.1 of metadata is

**Comment by feng-tao** [comment]
nice!

**Comment by feng-tao** [comment]
@jornh could this issue be closed now?

**Comment by jornh** [comment]
Merge of PR #123 is set up to automatically close it. So we’re close now with FE 1.1.0 tagged and pushed to docker!
