### ISSUE TITLE
Include tags in default search

### ISSUE THREAD

**Issue by markgrover** [lyft/amundsen#110]
Earlier we didn't know how tags would be used by users and we (more specifically, I) was worried that including tags in the default search may bring down search quality. So, currently to search based for tables with the tag, say `my_tag`, one has to explicitly do `tag:my_tag`.

However, seeing the usage of tags at Lyft and also hearing feedback from @swatro, I feel that tags should be included in the default search and we don't need to impose a special `tag:` to search. Of course, we can and should keep supporting that advanced search syntax but include the tag in the default search too.

**Comment by feng-tao** [comment]
We currently collect all the tags and push to ES table document(https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/extractor/neo4j_search_data_extractor.py#L36). @markgrover  Could you elaborate on the request? FYI the normal search doesn't provide exact search mechanism hence we build the category search.

**Comment by markgrover** [comment]
Thanks! Currently say if my table is tagged `my_tag` I type just `my_tag` in the search, it doesn't show any results. Is that right?

My request was to include tags in the weighted search so when simply `my_tag` is typed, the tagged tables show up. Of course if there's a table named `my_tag` that would show up too. I wasn't requesting exact search, but just the default search to also include tags as a feature.

Does that make sense?

**Comment by feng-tao** [comment]
@markgrover I think if it is single word it will show in the result. The issue is the ES will break down the term with other delimiter during search. Also there is no usage for the tag which will end up in the end of the results.
