### ISSUE TITLE
add example of how to load tag data to sample data loader

### ISSUE THREAD

**Issue by javamonkey79** [lyft/amundsen#129]
## AC
* Sample data loader would be update to load in tag data from csv
* csv examples would be updated

##
Example data from the front end:
![image](https://user-images.githubusercontent.com/1403289/66419424-f7134400-e9b8-11e9-8f61-d4d4fb66ad0a.png)

**Comment by feng-tao** [comment]
hey @javamonkey79 , currently tags are manually entered through UI.  If you click the button, I think you should be able to enter new tag.

If you want to load in batch from csv, I think we need a csv extractor which currently doesn't exist with a tableTag model.

**Comment by jornh** [comment]
Alternatively to introducing a tableTag model it looks like one could use the already existing optional parameter here:

https://github.com/lyft/amundsendatabuilder/blob/1.4.8/databuilder/models/table_metadata.py

**Comment by Mikhail-Ivanov** [comment]
@jornh probably you've meant this parameter:
https://github.com/lyft/amundsendatabuilder/blob/4d69b6afc4689193ab42346da4b4e6a456fca703/databuilder/models/table_metadata.py#L137

But yes, I think that existing domain model already supports tags. Created PR for this issue

**Comment by jornh** [comment]
Yep, you’re absolutely right! Didn’t spot I hit the column related class. That’s what happens when you look at code before coffee ☕️;)
