### ISSUE TITLE
Provide a FE or generic FAQ 

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#131]
E.g good to mention about how to custom FE CSS to be user's team/company specific CSS, how to custom tool's logo etc.

**Comment by feng-tao** [comment]
cc @danwom @ttannis 
per our today's lunch meeting with Kate

**Comment by jornh** [comment]
I believe the search introduced in #393 does a great job in fixing this need. Try searching for e.g. “logo” or “css”:

![504E9DF0-8C36-455F-BAE2-7E0335B61407](https://user-images.githubusercontent.com/766423/79717085-ed0fbd80-82d8-11ea-89c8-6e067190c6e3.jpeg)
