### ISSUE TITLE
amundsenfrontend local build fails

### ISSUE THREAD

**Issue by rahulraina7** [lyft/amundsen#136]
npm install crashes.

> Building amundsenfrontend
> Step 1/15 : ARG METADATASERVICE_BASE
> Step 2/15 : ARG SEARCHSERVICE_BASE
> Step 3/15 : FROM node:8 as node-stage
>  ---> c6b759d73b9d
> Step 4/15 : COPY . /app
>  ---> 1d08616dc459
> Step 5/15 : WORKDIR /app/amundsen_application/static
>  ---> Running in 46e8308d59b3
> Removing intermediate container 46e8308d59b3
>  ---> 2fa2de7ed1d8
> Step 6/15 : RUN npm install
>  ---> Running in 98701d7e6ece
> npm ERR! Maximum call stack size exceeded
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-10-17T06_03_56_431Z-debug.log
> ERROR: Service 'amundsenfrontend' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1

**Comment by jornh** [comment]
@rahulraina7 - what are exact steps to reproduce? Looks like it's https://github.com/lyft/amundsen/blob/master/docs/developer_guide.md#local-development you follow - but better to be sure. Also any other info you think is relevant regarding your environment (constraints etc.)? 

@ttannis any idea what the cause could be? Can you reproduce it?

**Comment by jornh** [comment]
@feng-tao would it be worth setting up CI (or rather ci/CD?) here in the umbrella ☂ repo?

It could check (some/all?) local development steps above and also spin up up a Quickstart instance and thus check the official Docker Hub images at https://hub.docker.com/u/amundsendev

This also relates a bit to what @friendtocephalopods suggested on Slack the other day with spinning up a e.g. a Neo4j metadata backend for tests

**Comment by danwom** [comment]
I did some initial investigation and hit some snags. While I continue my investigation, here are my notes:

1. I went through the default docker-compose and deployed without incident.
2. Based on `Step 6/15 : RUN npm install`, it looks like @rahulraina7 is using the older version of the docker file while I am using the newer version (updated by @jornh). 
3. I made local changes and started a local docker-compose build. This failed, but at a later step than noted above. (error below)




```
Step 15/19 : RUN pip3 install -r requirements3.txt
... 
...
Building wheel for typed-ast (setup.py): started
  Building wheel for typed-ast (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:

   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5cfassme/typed-ast/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5cfassme/typed-ast/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ya32cw50 --python-tag cp38
       cwd: /tmp/pip-install-5cfassme/typed-ast/
  Complete output (20 lines):

... 
...
unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for typed-ast
...
...
ERROR: Service 'amundsenfrontend' failed to build: The command '/bin/sh -c pip3 install -r requirements3.txt' returned a non-zero code: 1

```

**Comment by feng-tao** [comment]
we need to pick up @jornh's change and update the docker-compose script version.

**Comment by danwom** [comment]
Updating local dockerfile to https://github.com/lyft/amundsenfrontendlibrary/pull/316/files fixed `typed-ast` install issue for me. 

I went back and checked out the older dockerfile but was unable to reproduce the npm install failure. From what I can tell, this seems to be an NPM and it doesn't seem like our dockerfile specifies a version of npm. I don't know enough about docker to know what the default version of NPM would be or if it uses whatever is installed on your local environment.

@rahulraina7 can you let us know what version of NPM you are using?

**Comment by jornh** [comment]
@rahulraina7 any news/input?

To add a bit to @danwom's suggestion/request re. NPM version in https://github.com/lyft/amundsen/issues/136#issuecomment-543375166 just above I guess the answer would be that it's the one that is inside your `node:8` image ...

For comparison I just ran `docker run -v node:8 npm version` which pulled a fresh node:8 (because I had nuked any old docker node:8 images before that) and got:

```
$ docker.exe run node:8 npm version                                                                                                  { npm: '6.4.1',                                                                                                                                                   ares: '1.10.1-DEV',
  cldr: '32.0',
  http_parser: '2.8.0',
  icu: '60.1',
  modules: '57',
  napi: '4',
  nghttp2: '1.39.2',
  node: '8.16.2',
  openssl: '1.0.2s',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.23.2',
  v8: '6.2.414.78',
  zlib: '1.2.11' }
```

**Comment by rahulraina7** [comment]
Sorry, somehow I cannot reproduce this. I am not sure what changed.
