### ISSUE TITLE
Add table_stats to sample data loader

### ISSUE THREAD

**Issue by samshuster** [lyft/amundsen#158]
# Acceptance Criteria

example table_stats is added to sample data loader so we can see stats for a few tables when starting up amundsen.

**Comment by samshuster** [comment]
https://github.com/lyft/amundsendatabuilder/pull/159

**Comment by jornh** [comment]
BOOM! That was quick - guess you just beat Dave C to the finish line. And that this issue can be closed -though I must admit I liked his 🙊 stats better!

**Comment by feng-tao** [comment]
thanks @samshuster for the contribution. The change is merged.

**Comment by samshuster** [comment]
@jornh ah the 🐵 stat was much better!
I checked in with Dave C before hand to make sure he wasn't putting out a PR today, so went ahead and did it. Hopefully didn't step on anybody's toes.

**Comment by jornh** [comment]
Great team spirit there!
