### ISSUE TITLE
Production Installation guidelines

### ISSUE THREAD

**Issue by gonzalodiaz** [lyft/amundsen#16]
It would be great to have some documentation for guidelines to install Amundsen in production. Maybe with some Helm Chart to deploy it in a Kubernetes Cluster. Thanks!

**Comment by feng-tao** [comment]
https://github.com/lyft/amundsenfrontendlibrary/pull/216

**Comment by jornh** [comment]
@gonzalodiaz also see https://github.com/lyft/amundsenfrontendlibrary/issues/212 - let’s continue discussion over there. Appreciate if you could share your expectations for what such a helm chart should cover feature wise.

**Comment by jornh** [comment]
@gonzalodiaz did you get a chance to try out using Kompose.io to convert the compose file to a helm chart? Appreciate if you can share either success or failure 👍 

Also, if you agree #53 covers the same as this issue (and more) I suggest you (or the powers that be at Lyft) close this issue as a duplicate

**Comment by gonzalodiaz** [comment]
@jornh I haven't had the chance to review Kompose.io, but I will! 

I will close this issue in favor of #53 . Thanks!

**Comment by jornh** [comment]
@gonzalodiaz maybe the PR https://github.com/lyft/amundsen/pull/125 with a Helm chart will interest you - if you didn’t see it already. I’m sure review input would be welcome!

**Comment by gonzalodiaz** [comment]
@jornh I will definitely do it, once I have some bandwidth.
