### ISSUE TITLE
helm deployment does not allow for private image

### ISSUE THREAD

**Issue by javamonkey79** [lyft/amundsen#177]
Currently, the helm deployment template forces a templated path, for example:

```
image: {{ .Values.dockerhubImagePath }}/{{ .Chart.Name }}-{{ .Values.frontEndServiceName }}:1.0.9
```

But, if a user wants to provide an image from a private repo (e.g. dkr), then there is no way. Further, the frontendservice image has the version locked. 

Fixes:
1. A new variable should be checked and used, in case the full image is provided
2. The frontendservice version should be variable

**Comment by javamonkey79** [comment]
PR here https://github.com/lyft/amundsen/pull/179

**Comment by feng-tao** [comment]
thanks @javamonkey79 , change is merged.
