### ISSUE TITLE
Document local workflow

### ISSUE THREAD

**Issue by ttannis** [lyft/amundsen#18]
### Problem
We want to document how someone would go about getting set up to develop locally in Amundsen.
1. This is not intuitive for newcomers given our micro service architecture and multiple repositories/submodules. 
2. This is also difficult for folks who do not have Amundsen stood up in their company's internal development environments. For example at Lyft we are able to develop and test features with real data while hooked up to our internal infrastructure.

We have our docker compose script that helps standup a default version of Amundsen, but we currently lack any instruction on how to take what is accessible via this repository and set up an environment where a developer can modify and test changes in any part of Amundsen.

### Goal
Create support for and document how to get Amundsen running locally, with the ability to build and test local changes with dummy data.

### What I'm Considering
1. @jornh has mentioned hack that involves modifying `docker-amundsen.yml` to point to the image tag of the service in question some other dummy tag name, building the container for that service with those local changes, and re-running `docker-compose -f docker-amundsen-atlas.yml up`. (Jorn please correct me or give more detail if I misrepresented this idea) Two problems I faced here:
    * I couldn't get it to work, highly likely due to missing some detail or hack with docker-compose.
    * Folks have to deal with the overhead that is takes to build the local container, and to re-rerun the docker-compose script.

2. I then took a stab at something that worked better than I thought it would.
    * Stood up amundsenfrontend locally on port 5000 (according to instructions in the repo)
    * Stood up amundsensearch locally on port 5001
    * Stood up amundsenmetadata locally on port 5002
    * Ran `docker-compose -f docker-amundsen-atlas.yml up`, which only started the `neo4j_amundsen` and `es_amundsen` containers because the other ports were already in use.
    * Visiting `localhost:5000` now actually worked the same way it does for the quickstart. Except instead of this being the 5 docker containers working together it is now my local copy of amundsenfrontend, amundsemetadata, and amundsensearch utilizing the `neo4j_amundsen` and `es_amundsen` containers from the quickstart, so I actually get some dummy data. 
    * Made some changes in my local copy of `amundsenfrontendlibrary` and `amundsenmetadatalibrary` for kicks, could now see my changes locally. 
    ![image](https://user-images.githubusercontent.com/1790900/61259142-c4490f00-a72d-11e9-9ad2-b7d405deb1e8.png)
    * But what about instructions for `amundsendatabuilderlibrary`? TBD...my understanding is that the logic in databuilder can be tested locally via a couple different methods and I'm thinking the best place to document that is in the docs for that repo.

### What I'm Proposing
To document the second approach I described above, followed by filing some issues for the community to help us make this better . Some such ideas include:
1. Creating a script to do all the steps in the second option above. Besides changing the metadata and search wsgi's to run on different ports, all I did was change directories into each submodule and copy paste the local setup commands from each repo.
2. Richer dummy data. This local development approach still uses the neo4j and elasticsearch containers from the quick start, so the task of improving that will improve not just the quickstart, but standalone local development as well.

**Comment by jornh** [comment]
@ttannis Nice side effect you uncovered with the blocked ports. It can also be used to spin up more containers if you only need to work with one of them.

Also note that all the containers now supports port configuration through environment vars. That will simplify setup by not having to patch source config files. These env vars are already in use in the compose files, but lack other documentation. We might even consider defaulting the ports for the proxy containers to 5001 and 5002 that removes the need for config altogether!?! 😀

**Comment by ttannis** [comment]
### Update

I mistakenly believed my local instances of metadata/search had been able to connect to the neo4j and  elasticsearch docker containers. Once i started testing more I realized I must have been looking a stale tab.

However I switched back to some purely `docker-compose` based solution. I've been working on a `docker-amundsen-local.yml` that uses Jorn's ideas -- it will build the containers using the local code accessible in the upstream folders. This *appears* to work, will push a PR for this when I can for further discussion.

**Comment by ttannis** [comment]
Initial version added as part of #25.
