### ISSUE TITLE
provide first class support for csv ingestion

### ISSUE THREAD

**Issue by javamonkey79** [lyft/amundsen#186]
Currently, we have to use sample data loader, to ingest via csv. We'd like to see first class support for this, mostly to remove the need for SQL alchemy.

**Comment by javamonkey79** [comment]
@feng-tao we want to move away from sample data loader and this is the first step. I think we might want to consider retiring it altogether, or, providing an alternate sample loader that does not use SQL alchemy. I have this done locally, but, not sure if it would be confusing. wdyt?

**Comment by javamonkey79** [comment]
Closing this now that the PR is merged.

**Comment by javamonkey79** [comment]
Actually, need data builder pushed to pypi...

**Comment by feng-tao** [comment]
https://github.com/lyft/amundsendatabuilder/pull/174, waiting for coworker for a +1 :) will push to pypi once done

**Comment by feng-tao** [comment]
@javamonkey79 the latest databuilder version is released and pushed to pypi. Thanks :)

**Comment by javamonkey79** [comment]
Super! Thanks @feng-tao 🙇
