### ISSUE TITLE
Update the architecture diagram

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#19]
The architecture diagram(https://github.com/lyft/amundsen/blob/master/docs/architecture.md) is a bit outdated as it still shows we persist update description back to Hive metastore.

**Comment by jornh** [comment]
Another point to consider with the architecture document:

- mention that the two proxy services for search and metadata are configurable to either work with Neo4j/Elasticsearch or Apache Atlas - @verdan made a diagram as well https://github.com/lyft/amundsenmetadatalibrary/issues/7#issuecomment-472187736 I think it still roughly holds as a high level illustration.

**Comment by verdan** [comment]
> Another point to consider with the architecture document:
> 
> * mention that the two proxy services for search and metadata are configurable to either work with Neo4j/Elasticsearch or Apache Atlas - @verdan made a diagram as well [lyft/amundsenmetadatalibrary#7 (comment)](https://github.com/lyft/amundsenmetadatalibrary/issues/7#issuecomment-472187736) I think it still roughly holds as a high level illustration.

I'd rather provide a new one. this one is not accurate in case of search service.

**Comment by feng-tao** [comment]
I will add a new diagram.

**Comment by ttannis** [comment]
https://github.com/lyft/amundsen/pull/206
