### ISSUE TITLE
Add Quickstart sample data for badges

### ISSUE THREAD

**Issue by jornh** [lyft/amundsen#208]
What got introced in https://github.com/lyft/amundsenmetadatalibrary/pull/91 and frontend 1.2.0 should have sample CSV data load 

**AC**: Amundsen README screenshot is updated to showcase real life badges reflecting Roadmap mockups linked from https://github.com/lyft/amundsen/blob/master/docs/roadmap.md#search--resource-page-redesign

A follow up to this could be to update the roadmap.md to reflect that 1.2.0 delivered all under “current” afaics 

This is a good first issue.

**Comment by feng-tao** [comment]
thanks @jornh

**Comment by samshuster** [comment]
going to take a look at this one

**Comment by samshuster** [comment]
ok it turned out to be a bit more involved then I thought! Perhaps I missed something.

https://github.com/lyft/amundsendatabuilder/pull/185

**Comment by samshuster** [comment]
Ok now that the above is approved, I will get back to adding the screenshot to the main README.md as well as some information on how to customize the badge presentation in the frontend.

**Comment by samshuster** [comment]
https://github.com/lyft/amundsen/pull/263/files
