### ISSUE TITLE
amundsenfrontend on ECS not connecting to es & neo4j

### ISSUE THREAD

**Issue by eastTowest** [lyft/amundsen#210]
followed the steps on [installation-aws-ecs/aws-ecs-deployment.md](https://github.com/lyft/amundsen/blob/master/docs/installation-aws-ecs/aws-ecs-deployment.md) and I see all containers running just fine on ECS. However amundsenfrontend is not showing the sample data that I populated in elasticsearch and neo4j running in the same ECS cluster. 

`CloudWatch shows  `raise Exception('AUTH_USER_METHOD is not configured')`
Encountered exception: HTTPConnectionPool(host='amundsenmetadata', port=5000): Max retries exceeded Failed to establish a new connection: [Errno -2] Name or service not known'))`
CloudWatch shows  `raise Exception('AUTH_USER_METHOD is not configured')`

I wanna believe that [/docs/configuration.md#authentication](https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/configuration.md#authentication) & [amundsen/issues/27](https://github.com/lyft/amundsen/issues/27)  is irrelevant as all containers are located in the same cluster and the same ec2 instance as if it is running in local machines.

Thank you bunch for the help

**Comment by feng-tao** [comment]
I would suggest ask the question in our slack as Lyft currently doesn't use ECS for deploy. The community may have more idea on what is happening.
