### ISSUE TITLE
 [amundsen-kube-helm] Kubernetes neo4j setup bug

### ISSUE THREAD

**Issue by rsyi** [lyft/amundsen#234]
Hey amundsen team!
First of all, thanks for open-sourcing this project. Really excited to see where this goes, and hope I can make some contributions once I gain some familiarity with the codebase.

Found a small issue when installing neo4j:
`helm install templates/helm/neo4j --values ./amundsen-values.yaml --generate-name`
throws the following error:
`Error: validation: chart.metadata.version is required`

To fix this I took the following steps:

First, I tried explicitly adding `version: 3.3.0` to the `chart.yaml` file, but it throws another error:

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec): unknown field "resources" in io.k8s.api.core.v1.PodSpec
```

To address this, I deleted the `resources` block from the `deployment.yaml` file, which then allowed me to install the helm chart (and it starts up fine).

Not sure if this is a reasonable workaround (still debugging the overall setup). Otherwise, would love some advice on how to set this up correctly.

**Comment by feng-tao** [comment]
cc @javamonkey79

**Comment by feng-tao** [comment]
thanks @rsyi for reporting this issue :) tag Shaun @javamonkey79

**Comment by javamonkey79** [comment]
@rsyi can you post your amundsen-values.yaml file pls?

**Comment by rsyi** [comment]
No problem. Yes absolutely! Blocked out my dev dnszone, but otherwise this is it:

```
environment: "dev"
provider: aws
dnsZone: ####
dockerhubImagePath: amundsendev
searchServiceName: search
searchImageVersion: 1.4.2
metadataServiceName: metadata
metadataImageVersion: 1.1.5
frontEndServiceName: frontend
frontEndImageVersion: 1.1.1
frontEndServicePort: 80
```

**Comment by javamonkey79** [comment]
OK, so, I was able to reproduce this by upgrading my version of helm. Seems that there are some changes in helm 3 that are not compatible with what we have. 

My recommendation would be to use helm 2.x for now and someone will need to contribute an update such that this is helm 3 compatible. 

If you're on mac, you can install helm2 with:
```
brew install helm@2
brew link helm@2 --force
```

Also, if anyone wanders down the pathway of upgrading, and needing to revert, see [here](https://medium.com/@yujunz/install-an-old-version-formula-from-homebrew-b2848f5ecc00)

I won't have bandwidth for this any time soon, but maybe @lukelowery or @bryfox would be willing (part of the reason I'd rather not for now, is it requires updating your cluster too, I think).

**Comment by javamonkey79** [comment]
Also @rsyi you can try the command more vanilla...

I think that last argument could be the source of the issue:
```
helm install templates/helm/neo4j --values ./amundsen-values.yaml --dry-run --generate-name
helm install templates/helm/neo4j --values ./amundsen-values.yaml --dry-run
```

cmd 1 is yours and won't work on helm2 but works on helm3, so, maybe try and run it without the `--generate-name` arg...

**Comment by rsyi** [comment]
Ah yes that's it. I'm on helm v.3.0.2. 

Unfortunately, running the command without `--generate-name` arg with helm 3 throws the following errror:

```
Error: must either provide a name or specify --generate-name
```

which got me started on this whole mess.

Thanks for looking into this! I'll make a PR with an update to the docs.

**Comment by javamonkey79** [comment]
@rsyi do you have the PR to update the docs handy? If not, I can do it. It just needs to indicate helm 2, right?

**Comment by rsyi** [comment]
oops. completely slipped my mind, and haven't done this yet. and yeah, it just needs to indicate helm 2. feel free to do it :)

**Comment by javamonkey79** [comment]
@feng-tao I'd like this retitled to include [amundsen-kube-helm] as well, if possible.

**Comment by javamonkey79** [comment]
This is done with https://github.com/lyft/amundsen/pull/336

@rsyi please feel free to confirm and close

**Comment by rsyi** [comment]
Awesome!
