### ISSUE TITLE
PostgreSQL sample DAG bug?

### ISSUE THREAD

**Issue by darensin01** [lyft/amundsen#235]
Thanks to Tao Feng's tips on Slack, I managed to find the appropriate DAG script for my use case for PostgreSQL! However, I made some changes to `amundsendatabuilder/example/dags/postgres_sample_dag.py` along the way.

Line 76 should be:
`where_clause_suffix = textwrap.dedent("""where table_name in {schemas}""").format(schemas=SUPPORTED_SCHEMA_SQL_IN_CLAUSE)`

* The `.format(...)` part was missing previously.
* The `where` clause was selecting `table_schema` previously instead of `table_name`.
 
Are these bugs? Or these just happen to be platform/PostgreSQL version dependent? I'm using Windows and PostgreSQL version 12.

**Comment by feng-tao** [comment]
feel free to create a pr for us if you found a bug. I didn't keep track of all the sample script/dags :)

**Comment by feng-tao** [comment]
change is merged!
