### ISSUE TITLE
Database icons do not render in Firefox

### ISSUE THREAD

**Issue by benjaminjack** [lyft/amundsen#241]
The database icons for different tables (hive, postgres, etc.) do not render in Firefox on any pages in Amundsen. If I navigate to the path of the icon itself ('/static/icons/hive-icon.svg'), the icon renders when viewed directly. This makes me think that there's nothing wrong with the SVG icons themselves, but some kind of JS error that's preventing the icons from rendering correctly on the frontend.

The icons also appear fine on Chrome and Safari on the same machine, using the same version of Amundsen. I've tried clearing the cache and disabling all tracking protections in Firefox and the icons still don't render. 

Browser: Firefox 71.0
macOS 10.14.6

**Comment by feng-tao** [comment]
not sure why that's the case, but let me tag @danwom or @ttannis in case they know any other reasons.

**Comment by ttannis** [comment]
We're aware of the issue but it has been sitting in our internal backlog because ~98% of our users internally use Chrome. 

But if anyone wants to help pick this up since we can't guarantee it will ever get prioritized any time soon, I would suggest starting at our [icon styles](https://github.com/lyft/amundsenfrontendlibrary/blob/master/amundsen_application/static/css/_icons.scss#L59-62) and we will have to investigate how Firefox treats `mask` styles

**Comment by benjaminjack** [comment]
I investigated this a bit, but I think there are two issues. One is how Firefox treats `content` attributes and the `<img>` tag. Firefox does not support this attribute at all with images. This affects the hive table icon. I've reproduced the issue here: https://jsfiddle.net/Lbxhq8no/

Not sure how to address fixing this unless the underlying HTML tag is changed from `<img>` -> `<div>` or something like that.

I'm still investigating issues around how Firefox treats mask styles.

**Comment by benjaminjack** [comment]
Here's one possible solution that does not require modifying the underlying `<img>` tag:

https://jsfiddle.net/2geto8by/

It's still not quite a fix for the issue though because you need to know the width of the image in order to set the padding correctly.

**Comment by danwom** [comment]
Thanks for investigating @benjaminjack. I can take another look and push a PR sometime this week or next. As a last resort we can just use the `<img src="path"/>` as that will be most widely supported.

**Comment by jdavidheiser** [comment]
+1, I am also hitting this issue.

**Comment by Golodhros** [comment]
This should work now
