### ISSUE TITLE
BUG: docker-compose -f docker-amundsen-local.yml up

### ISSUE THREAD

**Issue by samshuster** [lyft/amundsen#246]
Local up fails due to requirements file rename.

ERROR: Service 'amundsenfrontend' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder496511433/requirements3.txt: no such file or directory

**Comment by samshuster** [comment]
simple fix for this coming soon

**Comment by samshuster** [comment]
https://github.com/lyft/amundsenfrontendlibrary/pull/378

**Comment by feng-tao** [comment]
thanks @samshuster , pr is merged!
