### ISSUE TITLE
BUG(?) OIDC missing introspection uri, incorrect path for user_info

### ISSUE THREAD

**Issue by samshuster** [lyft/amundsen#260]
I am not actually sure if this is a bug or not. All I know is that with the current oidc setup I was unable to get things to work. Looking at okta endpoints here 

https://developer.okta.com/docs/reference/api/oidc/#endpoints

I discovered that userinfo should be "{{ .Values.OIDC_ORG_URL }}/oauth2/{{ .Values.OIDC_AUTH_SERVER_ID }}/v1/userinfo"

and I also discovered that the introspection endpoint needs to be added as it was not being added to the client_secrets.json.

MR will come shortly. I will also include some more info in README.md about oidc with okta specifically.

**Comment by samshuster** [comment]
MR here: https://github.com/lyft/amundsen/pull/261/files

Happy to add more info to readme.

I also just remembered that another issue might be out for documenting oidc. I will try to find that issue.

**Comment by feng-tao** [comment]
thanks @samshuster
