### ISSUE TITLE
K8s Needs to set AmundsenFrontendBase for email notification

### ISSUE THREAD

**Issue by samshuster** [lyft/amundsen#271]
# Overview
- When mailing notification is turned on, it includes a link back to amundsen of the table/column that a description was requested on. It uses an environment variable ENVIRONMENT_BASE and falls back to localhost if not set.

# AC
- K8s can set FRONTEND_BASE environment variable via user defined property

**Comment by samshuster** [comment]
here we go:
https://github.com/lyft/amundsen/pull/272/files

**Comment by feng-tao** [comment]
the pr is merged. Thanks @samshuster
