### ISSUE TITLE
BUG: Standalone Column Model sortOrder UNQUOTED

### ISSUE THREAD

**Issue by samshuster** [lyft/amundsen#274]
Standalone Column Model does not add UNQUOTED to sortOrder. The result is alphabetical sort in neo4j for columns.

**Comment by samshuster** [comment]
https://github.com/lyft/amundsendatabuilder/pull/190

**Comment by feng-tao** [comment]
hey @samshuster , the issue could be closed. And feel free to ping me if you have a pr which could help us remove the standalone column model

**Comment by samshuster** [comment]
thanks. will do @feng-tao!
