### ISSUE TITLE
Setup a bot to auto update all the git submodules

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#29]

**Comment by jornh** [comment]
Looks like Envoy proxy is using a mechanism like what got added in this PR: https://github.com/envoyproxy/envoy/pull/3106

I noted it’s in use here: https://github.com/envoyproxy/envoy-filter-example/commits/master

**Comment by jornh** [comment]
If your happy with the job @dependabot does in #115 etc. it looks like this one is resolved?
