### ISSUE TITLE
Cannot connect on localhost:5000

### ISSUE THREAD

**Issue by scoutinhoGit** [lyft/amundsen#295]
Hi,

I have installed Amunden on my notebook.

All dockers images are running:

CONTAINER ID  IMAGE                                 STATUS           PORTS                     NAMES
1fd117c9f1c3  amundsendev/amundsen-frontend:1.2.0   Up 37 minutes    0.0.0.0:5000->5000/tcp    amundsenfrontend
19eb9409e80d  amundsendev/amundsen-metadata:1.1.5   Up 37 minutes    0.0.0.0:5002->5000/tcp    amundsenmetadata
c34ee4b58eaf  amundsendev/amundsen-search:1.4.2     Up 37 minutes    0.0.0.0:5001->5000/tcp    amundsensearch
89f7ec92d4fd  wbaa/rokku-dev-apache-atlas:0.1.4     Up 37 minutes    0.0.0.0:21000->21000/tcp  atlas_amundsen

I could not conect on http://localhost:5000. I recieve the error "ERR_CONNECTION_REFUSED"

Is there aything i could to to fix it?
Regards
Sergio

**Comment by scoutinhoGit** [comment]
Hi,

I have found this message in log of docker, but i do not know if it´s related with error when trying to access localhost on port 5000:

rokku_client created                                                                                                                                           
Done setting up Atlas types                                                                                                                                    
Done provisioning example data                                                                                                                                 
Creating Amundsen Entity Definitions...                                                                                                                        
Trying to create Table Entity                                                                                                                                  
Something wrong happened: HTTP request failed for POST http://localhost:21000/api/atlas/v2/types/typedefs: Service Unavailable 503: <html>                     
<head>                                                                                                                                                         
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>                                                                                       
<title>Error 503 </title>                                                                                                                                      
</head>                                                                                                                                                        
<body>                                                                                                                                                         
<h2>HTTP ERROR: 503</h2>                                                                                                                                       
<p>Problem accessing /api/atlas/v2/types/typedefs. Reason:                                                                                                     
<pre>    Service Unavailable</pre></p>                                                                                                                         
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.14.v20161028</a><hr/>                                                                         
</body>                                                                                                                                                        
</html>   

Regards 

Sergio

**Comment by feng-tao** [comment]
@scoutinhoGit how do you start Amundsen or do you use any docker compose file? Recently we update the default port for search/metadata which could be related.

**Comment by scoutinhoGit** [comment]
Hi,

I have followed instructions of GITHUB and executed this command:

 docker-compose -f docker-amundsen-atlas.yml up

I tried in different machines to run ALTAS option or NEO4J .. but in even trials, i could not connect to   localhost port 5000 .. i even tried 5001, 5002 ,5003 or 5004.

I have executed the text in a windows machine (win 10 pro) with DROPBOX TOOLS installed.

Best reggards,

Sergio

**Comment by scoutinhoGit** [comment]
Hi,

I have stopped dockers machine and tried to run it again with ATLAS OPTION.

Following the logs after starting, it appears that dockers startup freezes with this message:

```
atlas_amundsen      | Trying to create Reader <-> Metadata Entity
atlas_amundsen      | Already Exists, updating Reader <-> Metadata Entity
atlas_amundsen      | Applied Reader <-> Metadata Entity Definition
```

I do not know it if it is an error or a commom message. But no other message appears in logs after  many messages of this type.

Regards,

Sergio

**Comment by scoutinhoGit** [comment]
Hi,
Filnaly i have discovered that amundsen does not work on a windows environment with docker tools installed. I have repeated the instructions on a ubuntu machine withou problems.  Thanks ! Sergio

**Comment by scoutinhoGit** [comment]
This issue can be closed now
