### ISSUE TITLE
User responses from various APIs are inconsistent

### ISSUE THREAD

**Issue by danwom** [lyft/amundsen#296]
The user objects returned by various APIs have different subsets of fields. Some of these issues were addressed by various PRs from @friendtocephalopods, but we should go one step further.

Frontend currently tries to [sanitize these user objects](https://github.com/lyft/amundsenfrontendlibrary/blob/0bbbed00169a1d376db510412b754260e7d3bc70/amundsen_application/models/user.py#L75-L93) but should expect better data from various APIs.

For example the User objects in table owners and table readers contains just the email.

**Comment by feng-tao** [comment]
@danwom I think the history context is that table owner/reader could be any email as it just relies on user input. E.g if an user add a new team email which it hasn't indexed yet, there are no other infos to fill other fields of the user objects.

**Comment by friendtocephalopods** [comment]
I think in that case we should still use the same User object and just make the other fields optional. WDYT?

**Comment by jinhyukchang** [comment]
Need to dive deeper to see fields mismatching vs frontend dealing with optional fields but
would it be sufficient to have these fields in User schema:
`user_id`
`email`
`full_name`
`display_name`

and deprecate `name` replaced by `full_name`?

**Comment by worldwise001** [comment]
I am curious at how users are populated by internal auth mechanisms at other companies. At Square we populate username, since that is globally unique, and no user can reuse an existing username. For this reason I am inclined to make user_id required, and the rest optional.

user_id
email
full_name
display_name

as a set of sufficient fields in the User schema is totally fine.

**Comment by worldwise001** [comment]
Specifically here the username != email, and the email address is not necessarily <username>@squareup.com

**Comment by danwom** [comment]
@worldwise001 I agree, `user_id` should be required.

In fact I think all resources (user, table, dashboard) should come pre-baked with a unique id. I would suggest using the same field name to be consistent (currently `user_id`, `key`, and `uri`). We could then add a `type` field so the combination of `id` and `type` would be universally unique, or we can bake the type into the `id` like `"id": "user:danwom"`

**Comment by feng-tao** [comment]
@danwom what id are you referring to? across the whole system or just fe? if former, we have key uri across the stacks.

**Comment by danwom** [comment]
@feng-tao the former for sure. I don't think we currently expose `uri` for tables, but I know its planned for dashboards. Does it make sense for users to have uri?

**Comment by feng-tao** [comment]
I assume the issue could be closed now. Feel free to reopen if it is not the case.
