### ISSUE TITLE
Setting front end ImportError: cannot import name 'HTTPStatus'

### ISSUE THREAD

**Issue by satishjb** [lyft/amundsen#30]
python3 amundsen_application/wsgi.py
Traceback (most recent call last):
  File "amundsen_application/wsgi.py", line 2, in <module>
    from amundsen_application import create_app
  File "/home/satish/projects/amundsenfrontendlibrary/venv/lib/python3.4/site-packages/amundsen_frontend-1.0.6-py3.4.egg/amundsen_application/__init__.py", line 9, in <module>
    from amundsen_application.api.v0 import blueprint
  File "/home/satish/projects/amundsenfrontendlibrary/venv/lib/python3.4/site-packages/amundsen_frontend-1.0.6-py3.4.egg/amundsen_application/api/v0.py", line 3, in <module>
    from http import HTTPStatus
ImportError: cannot import name 'HTTPStatus'

**Comment by feng-tao** [comment]
which python3 and are you in virtual env ?

**Comment by satishjb** [comment]
https://github.com/lyft/amundsenfrontendlibrary/blob/master/docs/installation.md

Yes using virtual. with python3.4 i got this error

but with python 3.6 i am getting

Searching for responses==0.9.0
Reading https://pypi.python.org/simple/responses/
Download error on https://pypi.python.org/simple/responses/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'responses' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for responses==0.9.0
error: Could not find suitable distribution for Requirement.parse('responses==0.9.0')

**Comment by jornh** [comment]
https://docs.python.org/3/library/http.html#http.HTTPStatus says that statuscodes directly in the HTTP package was new in 3.5. So I think we have the reason for the error with Python 3.4.

**Comment by jornh** [comment]
I see responses version 0.9.0 available both as a tar.gz and a .whl at https://pypi.org/simple/responses/

**Comment by feng-tao** [comment]
thanks @jornh for the debugging!

**Comment by jornh** [comment]
@satishjb did you resolve the Pypi download issue you had with Python 3.6? (which I gave an answer to in https://github.com/lyft/amundsen/issues/30#issuecomment-517542377)

anything more anctionable for the Amundsen project to do here? 
If you agree there isn't more for the project to do please close this issue.

**Comment by satishjb** [comment]
@jornh I just tried and was successful in getting the frontend running in 3.5 as per your comment.

Thanks I am closing the issue.
