### ISSUE TITLE
Unable to connect to es_amundsen  using the sample data load script after running snowflake loader 

### ISSUE THREAD

**Issue by ak93-ak93** [lyft/amundsen#304]
We are getting an Unable to connect to es_amundsen  using the sample data load script after running snowflake loader . We are able to test successfully from the search interface on port 5000 and we can see the logs showing the search working . However when trying to load the data from sample loader the second time after loading snowflake sample we get the connection refused on port 9200

**Comment by jornh** [comment]
On what version(s) of databuilder and Amundsen Search service are you experiencing this?

**Comment by feng-tao** [comment]
not familiar with port 9200...like @jornh mentioned, how did you run the sample loader for snowflake?

**Comment by ak93-ak93** [comment]
resolved the issue by increasing the memory utilization.
