### ISSUE TITLE
2.0.0 databuilder change breaks HiveTableMetadataExtractor

### ISSUE THREAD

**Issue by rsyi** [lyft/amundsen#306]
The recent refactor to 2.0.0 causes the HiveTableMetadataExtractor to fail:
https://github.com/lyft/amundsendatabuilder/commit/dac8110d333f6dbc0e0f40c8d9c5e152ffa43775

I think it's because `schema` is a reserved keyword in my Hive metastore (though I'm not entirely sure). At least  reverting `schema` -> `schema_name` appears to fix the problem. I'll send a PR through, but wanted to flag this, in case this causes problems with other extractors.

**Comment by rsyi** [comment]
A note: it may be useful in the future to mock less in the unit tests so stuff like this can be caught.

Something like this might work?
https://stackoverflow.com/questions/31459439/testing-hive-spark-python-programs-locally

**Comment by feng-tao** [comment]
@rsyi thanks for reporting!, I add one comment to your pr. But I agree that we should have a better way to test this...
