### ISSUE TITLE
The most recent refactor schema_name -> schema causes schema to be "undefined" and table pages to break

### ISSUE THREAD

**Issue by rsyi** [lyft/amundsen#309]
I went ahead and rebuilt a bunch of docker images manually based on all the libraries to accommodate the recent databuilder refactor, and noticed that the recent refactor in the other libraries (schema_name -> schema seems to be breaking the build... I tested this by rebuilding the docker images without the most recent commits from @friendtocephalopods, and they work fine.

E.g. see below -- my table, which has a schema "hive" is now "undefined". Clicking the table also now says "Something went wrong...".

![image](https://user-images.githubusercontent.com/28232885/75593171-5261d380-5a39-11ea-8b43-f77102b76faa.png)

Don't understand all the references well enough to debug this atm, but thought I'd flag it. :) I'm pretty sure it's just one small miss in the refactor somewhere. @friendtocephalopods maybe you can help?

**Comment by jinhyukchang** [comment]
Hi @rsyi ,

We haven't faced this issue and I wonder if you have published ES index with updated databuilder.

https://github.com/lyft/amundsen/blob/master/docs/faq.md#amundsen-1x---2x-migration-guide

**Comment by rsyi** [comment]
Huh weird. Yeah I'm using an updated databuilder too. Let me make sure everything is migrated correctly, and I'll get back to you. I'll try it with the pre-built docker images.

**Comment by rsyi** [comment]
Okay! It looks like it works with the pre-built docker images... I'll close this for now, and re-open if I can recreate this. I'm guessing there was a commit somewhere I was missing. Thanks, @jinhyukchang.

**Comment by feng-tao** [comment]
@rsyi thanks for verifying !
