### ISSUE TITLE
Add a doc on all the supported model for databuilder

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#320]
Currently we don't have document for supporting models in databuilder. We should add that.

**Comment by samshuster** [comment]
hey @feng-tao would this doc be basically describing each of the models in the model package?

Like TableMetadata, ColumnMetadata etc. ?

**Comment by feng-tao** [comment]
correct, and how to use it in what cases etc? Because sometimes we provide the model but not the extractor as different companies could gather the same metadata differently.

**Comment by samshuster** [comment]
ok here is a start at it: https://github.com/lyft/amundsendatabuilder/pull/217/files

Let me know what else you are looking for, for a given model and I can adjust.

**Comment by feng-tao** [comment]
we could close now.
