### ISSUE TITLE
[amundsen-kube-helm] [technical debt] move to neo4j\elasticsearch charts

### ISSUE THREAD

**Issue by javamonkey79** [lyft/amundsen#327]
### AC
* update the amundsen helm chart, to have dependencies on [neo4j](https://github.com/helm/charts/tree/master/stable/neo4j) and [elasticsearch](https://github.com/helm/charts/tree/master/stable/elasticsearch) charts
* remove the neo4j and elasticsearch charts from this project

### Reasoning
* we do not need to maintain a copy of these charts, since they already exist

**Comment by javamonkey79** [comment]
@feng-tao please assign to me and label with k8s

**Comment by javamonkey79** [comment]
@feng-tao 
> @feng-tao please assign to me and label with k8s
bump

**Comment by javamonkey79** [comment]
Ok, I have investigated this. It turns out that the helm chart for neo4j is missing at least 2 features that I've noticed:

* providing custom configuration
* allowing for custom service changes, such as change to load balancer, additional annotations

While the second one is not strictly necessary, I think the 1st one is and is therefore a blocker for doing this task.

**Comment by feng-tao** [comment]
Assign the ticket to you :)

**Comment by javamonkey79** [comment]
@feng-tao I'm going to leave this open, I thought moving to neo4j chart was not possible, but, in fact now I think it is. However, I don't have any more time to implement it.

**Comment by feng-tao** [comment]
@javamonkey79  sounds good, thanks a lot for all the k8s helm contributions. Curious are you working on some other projects and not Amundsen soon in your team? And how's the Amundsen usage so far at Edmunds ?

**Comment by javamonkey79** [comment]
> Curious are you working on some other projects and not Amundsen soon in your team? 

Yeah, I've taken on some new work and will likely be unable to do much more with Amundsen for a little while. 

> And how's the Amundsen usage so far at Edmunds ?

I think @samshuster could answer it better, tbh. I've only been focused on the k8s side, so, I've drifted quite a bit.

**Comment by samshuster** [comment]
So far It has been well received by management, and by users via surveys, but it still has a long way to go with active adoption. I think what is going to happen is that there will be a pause in feature integration on our side while we try to boost usage and get feedback with what is already there. Another team might also try to integrate with different datasets.

**Comment by rsyi** [comment]
FYI @javamonkey79  and @feng-tao, the docker image that's used by the official neo4j helm chart is the 4.x enterprise edition, and I think (based on this [this announcement](https://neo4j.com/open-core-and-neo4j/)) that this edition legally requires an enterprise license. Maybe that's fine for Edmunds, but probably not for the majority of the OS community :)

It may make sense to stay on the community edition for now, and close this?

**Comment by feng-tao** [comment]
thanks @rsyi for the information. Yeah, we could close this for now. Lyft is also on community version(not k8s though) neo4j.

**Comment by MrwanBaghdad** [comment]
@feng-tao  I believe we need to revisit this issue as I can see from the chart's config that the community version is allowed [here](https://github.com/neo4j/helm-charts/blob/dev/neo4j-standalone/values.yaml#L11-L14), I also believe that annotations and configuration for init containers are addressed.
