### ISSUE TITLE
Unique identifier of User entity is email, but should be configurable

### ISSUE THREAD

**Issue by verdan** [lyft/amundsen#34]
In the current implementation, the unique/required identifier and required field is `email`, and I think that should be configurable. Or, we can introduce a new field username which is required and email can be optional. In case where username and email address are same, simply fill both attributes with the email address. 

**Use Case:** 
At ING, we do use corporate keys, which are totally unique and can not be changed, but email address can be changed (for example, name change after marriage, change of domain part based on geolocation etc.) So, to handle that scenario we can have corporate key as the unique identifier. It would make no sense and may be confusing for the users if we send corporate key in email address field and also, then there would not be an attribute to put email address. 

Happy to discuss in details, and make the change in both frontend and backend, once we finalize this. 

@feng-tao @jinhyukchang

**Comment by ttannis** [comment]
@verdan this issue is resolved now that we have an official `user_id` correct? Will go ahead and close please comment if you have any further issues in this space.
