### ISSUE TITLE
The link to ModeDashboardExtractor in amundsendatabuilder/README.md is broken

### ISSUE THREAD

**Issue by fBedecarrats** [lyft/amundsen#348]
The last sentence of the readme file is:

> To see in action, take a peek at [ModeDashboardExtractor](https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/extractor/dashboard/mode_dashboard_extractor.py)

It points at https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/extractor/dashboard/mode_dashboard_extractor.py, which no longer exists.
I guess it should point at: https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/extractor/dashboard/mode_analytics/mode_dashboard_extractor.py

**Comment by feng-tao** [comment]
@fBedecarrats thanks, could you create a pr for us?
