### ISSUE TITLE
Add a doc in amundsenfrontendlibrary regarding how to use the announcements feature

### ISSUE THREAD

**Issue by ttannis** [lyft/amundsen#358]
Context: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1585689296183500

**Comment by feng-tao** [comment]
could just put it at https://github.com/lyft/amundsen/blob/master/docs/faq.md

**Comment by ttannis** [comment]
The frontend repo already has a section where we have examples and doc for the base clients, so I'll be putting it there.

**Comment by jornh** [comment]
The faq doc could have an entry: “How do I configure frontend?” See https://github.com/lyft/amundsenfrontendlibrary/blob/v2.1.0/docs/configuration.md (that small document got some already extensive but with room for contributions underlying sections on Flask and React respectively)

This only said _halfway in jest_ 😜 - actually an honest proposal. Feel free to improve on wording.
