### ISSUE TITLE
Instructions for installing amundsen on k8 using helm not correct?

### ISSUE THREAD

**Issue by Jwan622** [lyft/amundsen#372]
I am trying to run this:

```
helm install dsci-amundsen templates/helm/amundsen --values impl/helm/dev/values.yaml
Error: failed to download "templates/helm/amundsen" (hint: running `helm repo update` may help)
✘-1 18:01 ~/dsci-amundsen [master L|…4] $ helm search hub templates/lyft/amundsen
No results found
```

to no avail. What can I do? What am I missing? Where is the helm chart? I'm an newb at using helm.

@javamonkey79

**Comment by javamonkey79** [comment]
@Jwan622 you need to clone the repo https://github.com/lyft/amundsen/tree/master/amundsen-kube-helm

**Comment by Jwan622** [comment]
`helm install templates/helm/amundsen --values impl/helm/dev/values.yaml`

I'm reading [this](https://helm.sh/docs/intro/using_helm/) and so does this mean that `templates/helm/amundsen` is the release name and the values file is in location ` impl/helm/dev/values.yaml`? I get 👍 

```
helm install templates/helm/amundsen --values impl/helm/dev/values.yaml
Error: must either provide a name or specify --generate-name
```

as the error. I just git cloned the entire repo and ran `cd amundsen-kube-helm/`

**Comment by Jwan622** [comment]
What I did was:

1. git clone https://github.com/lyft/amundsen
2. ran `cd amundsen-kube-helm/`
3. and then ran:
```
helm install templates/helm/amundsen --values impl/helm/dev/values.yaml
Error: must either provide a name or specify --generate-name
```

What did I do wrong? What should I do?

**Comment by jornh** [comment]
@Jwan622 assuming you’re using helm 3 try - when in the `cd amundsen-kube-helm/` directory as @javamonkey79’s guide mentions:

```
helm install dsci-amundsen ./templates/helm/templates 
```

The `./templates/helm/templates` should match the relative path to where the helm chart is located. 

So this is only from memory as I’m currently not at my PC. I’ve got a doc update PR sitting locally - where I have it working with helm 3 - I’ll try to push when I can. But hoping this will bring you closer to a working solution.

The current README.md guide specifically mentions helm 2, and I think the relative chart path changed slightly in a recent PR.

**Comment by jornh** [comment]
Note the above will then just give you the default helm `values.yaml` config. You can feed it your own file by giving a path like e.g. `--values impl/helm/dev/values.yaml` 

Another tip is adding the `--debug` parameter to see what helm will send to k8s.

**Comment by jornh** [comment]
@Jwan622 please review and see if changes in #373 fixes the issue for you.

Further improvement suggestions to #373 to make the guide more clear is more than welcome. Thanks!
