### ISSUE TITLE
Total_read incremented?

### ISSUE THREAD

**Issue by haha150** [lyft/amundsen#381]
How is the total_read field incremented?

I see that the elasticsearch mapping for user has the fields total_read, total_follow and total_own, and i understand that the follow and own are updated in neo4j when you follow or own a dataset. However, how is the total_read field incremented and also how is elasticsearch updated with all three fields?

**Comment by jornh** [comment]
> How is the total_read field incremented?

Through usage data ingested via https://github.com/lyft/amundsendatabuilder/blob/master/docs/models.md#columnusagemodel.

> how is elasticsearch updated with all three fields?

It's updated via Databuilder runs - see https://github.com/lyft/amundsen/blob/master/docs/architecture.md#databuilder and the illustration in the top of that document. It's actually implemented as Extract-from-Neo4j -> Load-into-ES.

----

For both cases above check examples of Databuilder usage in the Quickstart example loader - which load from dummy CSV sources.

**Comment by haha150** [comment]
hmm, okay, but if i search for a dataset, and perhaps click on it, where is the backend informend that the dataset has been read ?

**Comment by jornh** [comment]
The ranking popularity is not based on just popularity in Amundsen, but rather "real usage" by increasing the read count for each (SQL) query hitting that table.

Here's a bit of explanation in the Amundsen technical walk-trough blog post:
https://eng.lyft.com/open-sourcing-amundsen-a-data-discovery-and-metadata-platform-2282bb436234#ba9a

As mentioned above, the ingest is happening through https://github.com/lyft/amundsendatabuilder/blob/master/docs/models.md#columnusagemodel

Depending on what data source(s) you have, and how you query it - what plumbing you need to add may differ. On the Slack channel here's some coverage of approach/support/considerations. I think I also saw a Redshift related script floating around in there. That hasn't, yet, been contributed to the Databuilder repo though.

**Comment by haha150** [comment]
ok thanks.

another thing, can you also point me to what commands you run to backup neo4j?

**Comment by jornh** [comment]
It’s in the Kubernetes Helm Chart here: https://github.com/lyft/amundsen/blob/master/amundsen-kube-helm/templates/helm/templates/neo4j-s3-backup.yaml

But can of course also just be based on that for other contexts

**Comment by haha150** [comment]
yes exactly but where are the "CALL apoc.export.cypher.schema(..)" commands executed ?

**Comment by jornh** [comment]
It looks like you're may be in the right place. But they require install of some Neo4j addons.

I haven't gotten to fool around with the latest bits (recently added to K8s) in this area yet myself. But maybe to supplement you can cross-reference an older writeup I drafted: https://github.com/lyft/amundsen/issues/53#issuecomment-516159598

**Comment by haha150** [comment]
oki, thanks!

another question, sorry. Do you keep versions of datasets that are ingested? for example if a dataset changes over time, how do you keep track of its changes and make sure the users can see that the dataset has changed or is updated?

**Comment by jornh** [comment]
Not currently, if it's this you are talking about: open issue/roadmap item https://github.com/lyft/amundsen/issues/45#issuecomment-548245405
