### ISSUE TITLE
Move antlr4 dependency from python 2 to python 3

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#40]
All three microservices for Amundsen(data portal) could run on both python 2.x or python 3.x. The data ingestion library(amundsendatabuilder) could run only on python 2.x because of `antlr4-python2-runtime`.

It is used in [ColumnUsage parser](https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/sql_parser/usage/presto/column_usage_provider.py). We should explore and see if we could move the dependency to python 3(e.g. https://github.com/antlr/antlr4/tree/master/runtime/Python3)

**Comment by jornh** [comment]
@feng-tao Are you folks at Lyft still needing Databuilder Airflow on python 2.7? If so have you got any timeline for moving to Python 3?

**Comment by feng-tao** [comment]
cc @jinhyukchang hey @jornh good point, actually Lyft internally does use antlar to get presto query log parsing any more as there are lots of edge cases not handled...We are currently in the process of migrating our Airflow infra to latest upstream and py3 (targeting end of q1). But I think we could remove antlar code and make the repo py2,py3 compatible, WDYT?

**Comment by jinhyukchang** [comment]
@feng-tao Sounds good to me. May be an announcement of removal is needed for the one that is using it? (Not aware of any though)

**Comment by feng-tao** [comment]
@jinhyukchang agree, @jornh, currently we are a bit behind the schedule, will remove the code once we are free up.
