### ISSUE TITLE
Hive Extractor under Postgresql Metastore

### ISSUE THREAD

**Issue by rqmulti** [lyft/amundsen#431]
I had problems using the section extractor using the metastore in postgresql due to a different sql syntax,

below an example of the query that works for Postgres

`SELECT source.* FROM
    (SELECT t."TBL_ID", d."NAME" as "schema", t."TBL_NAME" as name, t."TBL_TYPE", tp."PARAM_VALUE" as description,
           p."PKEY_NAME" as col_name, p."INTEGER_IDX" as col_sort_order,
           p."PKEY_TYPE" as col_type, p."PKEY_COMMENT" as col_description, 1 as "is_partition_col",
           CASE WHEN t."TBL_TYPE" = 'VIRTUAL_VIEW' THEN 1 ELSE 0 END "is_view"
    FROM "TBLS" t
    JOIN "DBS" d ON t."DB_ID" = d."DB_ID"
    JOIN "PARTITION_KEYS" p ON t."TBL_ID" = p."TBL_ID"
    LEFT JOIN "TABLE_PARAMS" tp ON (t."TBL_ID" = tp."TBL_ID" AND tp."PARAM_KEY"='comment')
    --{where_clause_suffix}
    UNION
    SELECT t."TBL_ID", d."NAME" as "schema", t."TBL_NAME" as name, t."TBL_TYPE", tp."PARAM_VALUE" as description,
           c."COLUMN_NAME" as col_name, c."INTEGER_IDX" as col_sort_order,
           c."TYPE_NAME" as col_type, c."COMMENT" as col_description, 0 as "is_partition_col",
           CASE WHEN t."TBL_TYPE" = 'VIRTUAL_VIEW' THEN 1 ELSE 0 END "is_view"
    FROM "TBLS" t
    JOIN "DBS" d ON t."DB_ID" = d."DB_ID"
    JOIN "SDS" s ON t."SD_ID" = s."SD_ID"
    JOIN "COLUMNS_V2" c ON s."CD_ID" = c."CD_ID"
    LEFT JOIN "TABLE_PARAMS" tp ON (t."TBL_ID" = tp."TBL_ID" AND tp."PARAM_KEY"='comment')    
    ) source
    --ORDER by tbl_id, is_partition_col desc;
`

**Comment by rqmulti** [comment]
Reference: https://community.cloudera.com/t5/Support-Questions/How-can-I-access-hive-metastore-tables/td-p/232278

**Comment by feng-tao** [comment]
I think you could provide your own sql to extract(https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/extractor/hive_table_metadata_extractor.py#L73) . It will only fall back to the default one if no sql is provided.

**Comment by rqmulti** [comment]
Awesome, well there's a missconfig in the hive dag example, 
'extractor.hive_table_metadata.extractor.sqlalchemy.{}'.format(SQLAlchemyExtractor.CONN_STRING):

i will try to fixe it, thanks by the way.

**Comment by feng-tao** [comment]
thanks, please raise us a pr if you find anything is missing or incorrect.
