### ISSUE TITLE
Running Amundsen behind an nginx reverse proxy 

### ISSUE THREAD

**Issue by abhilash1in** [lyft/amundsen#438]
I have the following `nginx` config:

```
server {
  listen 8080;
  server_name myhost;
  location /meta/ {
      proxy_pass http://localhost:5000;
      proxy_redirect off;
      proxy_http_version 1.1;
      proxy_set_header Host $host:$server_port;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
  }
}
```

When I visit `http://myhost:8080/meta/`, I expected to see Amundsen UI. The webpage loads, however, all the resource URLs for CSS and JS are incorrect and therefore, there are 404s.

For example, when the webpage tries to load `main.css`, it uses `http://myhost:8080/static/dist/main.css`, but it should have been `http://myhost:8080/meta/static/dist/main.css`

1. How do I host Amundsen behind an nginx reverse proxy?
11. How do I tell Amundsen to add a prefix (`/meta` in this case) to all resource URLs and API endpoints?

**Comment by jornh** [comment]
Your question 2. Is already identified as an issue in https://github.com/lyft/amundsen/issues/424 which has an associated WIP PR.

**Comment by ajitkshirsagar** [comment]
Unfortunately, the associated PR is closed and never merged.
@abhilash1in Did you find the solution?
