### ISSUE TITLE
Add Support of NOSQL database (i.e MongoDB, ElasticSearch, Solr)

### ISSUE THREAD

**Issue by NitendraKumar** [lyft/amundsen#440]
I have huge amount of data in ElasticSearch and MongoDB Cluster and I have requirement to provide meta data of its collection on some UI.

Amundsen has good support of nearly all famous RDBMS but I did not find any support of NOSQL.

Any help or example code which can help me to plug NOSQL data into Amundsen platform and available for user using the same architecture.

**Comment by feng-tao** [comment]
For elasticsearch, you could try https://github.com/preset-io/elasticsearch-dbapi which Amundsen supports dbapi extractors.

Not sure about mongodb.

**Comment by NitendraKumar** [comment]
Thanks for your help.
