### ISSUE TITLE
Feat: Semantic PR title check

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#459]
Leverage either [prlint](https://github.com/apps/prlint) or https://github.com/zeke/semantic-pull-requests to do semantic pr title check for each different repos.

**Comment by feng-tao** [comment]
cc @Golodhros @ttannis @dikshathakur3119 @jinhyukchang 
What do you guy think? I was talking to Marcos today and felt that this could help us to make the pr title cleaner which could benefit us to have a organized changelog.

**Comment by ttannis** [comment]
What features would we leverage, just the title pattern option or is there anything else?

**Comment by feng-tao** [comment]
mostly title pattern to follow this convention (e.g https://github.com/lyft/amundsendatabuilder/pull/265). Then I think if we built out changelog/milestone doc, it will be easier to understand which commit is for what purpose. It seems that quite some OSS projects have done this recently (e.g https://github.com/apache/incubator-superset/blob/master/.github/prlint.json for superset)

**Comment by ttannis** [comment]
I'm in favor of it, especially if we can leverage it for changelogs. So far it's been a very manual process of looking through old commits to try to write better release notes for the frontend releases where we tend to batch a several weeks of work.

**Comment by Golodhros** [comment]
Awesome!

I didn't know about prlint, it looks like a superior solution. It allows to also check the branch names, labels, the content of the PR and more. I would go with that one!

I would suggest to start with the PR title and some plain basic requirements for the PR description content.

**Comment by feng-tao** [comment]
sounds good, I just installed the prlint app on all six repos. I will create a simple prlint file for each repos.

**Comment by feng-tao** [comment]
https://github.com/lyft/amundsen/pull/460
