### ISSUE TITLE
Bookmarking (star) is disabled in Amundsen

### ISSUE THREAD

**Issue by ibnipun10** [lyft/amundsen#496]
## Summary
I am not able to click on the `star` icon next to table name to bookmark it. 

<img width="593" alt="Screenshot 2020-06-09 at 11 14 56 AM" src="https://user-images.githubusercontent.com/3518277/84110482-9e61e280-aa42-11ea-8ceb-e8e0d17a1f67.png">

The table is the sample table which is populated by the sample script. The behaviour for other tables from mssql are also the same

## Expected Behavior
It should allow to bookmark and should be shown in the mainpage

## Current Behavior
Not able to click on the `star` icon. It is disabled

## Steps to Reproduce
1. Installed Amunden on AKS using helm 3
2. Ran the sample data script and mssql script to populate with sample data as well as my custom mssql database 
3. Unable to click on the star icon

## Your Environment

* Amunsen version used: Master branch
* Data warehouse stores: 
* Deployment (k8s or native): AKS
* Link to your fork or repository: https://github.com/lyft/amundsen

**Comment by feng-tao** [comment]
cc @jinhyukchang @ttannis 
last time I tried sample loader which works, I wonder whether it is due to book mark feature refactor to be generic and accommodate dashboard use case.

**Comment by jornh** [comment]
The bookmarking relies on that there's a logged in user. In the Quickstart with docker-compose that's done with this hack configuring a single test user:

https://github.com/lyft/amundsen/blob/006199ab3180dfd7535885e035d3d0ca505f76e5/docker-amundsen.yml#L73-L77

With the Helm chart config of authentication is needed e.g. with OIDC - it's not clear from the issue posted if you did that @ibnipun10?

**Comment by ibnipun10** [comment]
No I am not doing that @jornh. Thank you. Can we plz add it to the docs as well? Is it possible to do a oauth authentication support with amundsen

**Comment by jornh** [comment]
See https://lyft.github.io/amundsen/authentication/oidc/ for what's currently there.

The. relatively new, documentation site has a quite good search function. As with anything documentation is an ongoing effort. Documentation for authentication can certainly be improved on.

**Comment by feng-tao** [comment]
i assume the issue is resolved now.
