### ISSUE TITLE
mysql integrate

### ISSUE THREAD

**Issue by fageiguanbing** [lyft/amundsen#497]
How to set username / password / port in `mysql_metadata_extractor.py`?

**Comment by jornh** [comment]
https://docs.sqlalchemy.org/en/13/dialects/mysql.html#dialect-mysql-mysqldb-connect

**Comment by fageiguanbing** [comment]
> I'd expect you can use https://docs.sqlalchemy.org/en/13/dialects/mysql.html#dialect-mysql-mysqldb-connect - if that's the driver you are using
> 
> That's a general pattern you can use for the extractors based on SQLAlchemy (and DBAPI)

Where can I set the URL?
```
mysql+mysqldb://root@/<dbname>?unix_socket=/cloudsql/<projectid>:<instancename>
```
I see `TableKey = namedtuple('TableKey', ['schema', 'table_name'])` in `mysql_metadata_extractor.py`, I guess I could edit all three('TableKey','schema', 'table_name').
Where is the configuration file, I am not a Python developer, this is very annoying for me

**Comment by jornh** [comment]
Ah sorry I didn’t notice you were mentioning the `Extractor` class, I misread it as a MySQL `sample_Xxx_data_loader.py`

You will have to wrap the Extractor in a Task in a Job Like shown in the diagram in https://github.com/lyft/amundsendatabuilder#concept

The Job is the one taking the connection string as documented in https://github.com/lyft/amundsendatabuilder#sqlalchemyextractor - there are examples of how it’s all put together in https://github.com/lyft/amundsendatabuilder/tree/master/example/scripts no one has put up an example for MySQL but all the ones based on sqlalchemy are very similar. It looks like the MySQL Extractor was made as a clone of the DB2 one so I would start with looking at that sample.

I hope this makes it a little less annoying to you 🙂

**Comment by fageiguanbing** [comment]
> Ah sorry I didn’t notice you were mentioning the `Extractor` class, I misread it as a MySQL `sample_Xxx_data_loader.py`
> 
> You will have to wrap the Extractor in a Task in a Job like shown in the diagram in https://github.com/lyft/amundsendatabuilder#concept
> 
> The Job is the one taking the connection string as documented in https://github.com/lyft/amundsendatabuilder#sqlalchemyextractor
> 
> There are examples of how it’s all put together in https://github.com/lyft/amundsendatabuilder/tree/master/example/scripts no one has put up an example for MySQL but all the ones based on sqlalchemy are very similar. It looks like the MySQL Extractor was made as a clone of the DB2 one so I would start with looking at that sample.
> 
> I hope this makes it a little less annoying to you 🙂

Thanks.
You mean I have to implement the logic myself， just like [https://github.com/lyft/amundsendatabuilder/tree/master/example/scripts](https://github.com/lyft/amundsendatabuilder/tree/master/example/scripts).
For example, if I want to implement Hive, I need to import Hive related `Extractor`.

**Comment by jornh** [comment]
Yes, correct!

**Comment by fageiguanbing** [comment]
> Yes, correct!

I got it, thank you.
