### ISSUE TITLE
Dashboard Feedback(feat): Initial Integration with Redash

### ISSUE THREAD

**Issue by jonhehir** [lyft/amundsen#515]
## Context

We have been evaluating dashboard support in Amundsen internally, using Redash as our initial dashboard product. The process of building an initial extractor that leveraged the Redash REST API was reasonably straightforward, and most things work, with some quirks noted below.

## Data Model/Product Discrepancies

One general area worth noting is that the data model for Redash dashboards does not perfectly match the current dashboard data model in Amundsen nor the feature set in Mode. (This is perhaps not surprising.) Discrepancies include:

- Redash does not have a dashboard description.
    - This is admittedly a very useful field, so we are auto-generating descriptions by either extracting text from the dashboard or extracting widget names and compiling them into a description.
    - While this works, it's worth noting that the link to "edit description in Redash" is not particularly relevant since we’re auto-generating descriptions. This is effectively an uneditable field for us.
- Dashboards do not have execution times or statuses in Redash.
    - Individual queries have a last refreshed concept, although I believe accessing this through the API requires actually fetching the most recent query results for each query.
    - There is no concept (that I'm aware of) of a successful vs. failed query (let alone dashboard) execution.
    - We are currently simply not populating the dashboard execution timestamps in Amundsen.
- There are no dashboard groups in Redash.
    - This isn't necessarily a problem, and we just stash all dashboards into one group.
- Finally, this is not really a data model issue, but Redash does not expose view counts in a convenient way through the API. Right now we are leaving this field blank, which results in conspicuous view counters that all read 0. We may use direct DB access to pull these figures going forward.

## Concrete Issues/Suggestions

- Dashboard descriptions should support Markdown. Right now, our descriptions are being saved as Markdown but spit out like plain-text.
- Dashboard descriptions should support a completely uneditable mode, similar to the `UNEDITABLE_SCHEMAS` concept for table descriptions.
- On the front end, we should either be able to hide certain fields (e.g., last dashboard execution) or have certain fields automatically hidden if they have no value. (Every dashboard we have shows two December 1969 timestamps currently due to missing data.)
- Tags used for dashboards only (e.g., `test_dashboard`) show up on the Amundsen homepage with a count of 0.
- The link to view a query externally right now says "View in Mode." This should use the actual dashboard product name. This is the only Mode-specific naming I'm aware of currently, although there may be some others floating around.

**Comment by jonhehir** [comment]
I realize this issue is not really of the bug report or feature request format (and has a small laundry list at the bottom), but we wanted to share our initial experience with the beta dashboard feature with you guys. Please let us know if you have any questions or would like us to follow up with anything additional (e.g., creating individual tasks for the suggestions at the bottom).

Thank you!

**Comment by feng-tao** [comment]
thanks @jonhehir ! , very exciting that you get it working for redash. All the issues/ suggestions seem reasonable to me :)
cc @ttannis  @jinhyukchang

**Comment by feng-tao** [comment]
1. +1,  For Lyft, we got dashboard descriptions from mode API, but just haven't had time to do some change as table descriptions with markdown syntax(@ttannis  correct me if I am wrong)
2. will let @ttannis comment on the feasibility.
3. make sense
4. yeah, seems like a bug
5. agree, currently it is hardcoded(https://github.com/lyft/amundsenfrontendlibrary/blob/master/amundsen_application/static/js/components/DashboardPage/QueryListItem/index.tsx#L17). We could get it with metadata API product field? cc @Golodhros

**Comment by jinhyukchang** [comment]
@johnheir Congrats on the progress and thanks for the detailed feedback!

On the note of execution time, there are things we consider valuable to see how trustworthy the Dashboard is. Things such as popularity, relation with important tables, and execution time with status. 

We saw many unmanaged Dashboard that has very old last `refreshed` (in Redash term) timestamp, and some of them tried to be refreshed but has been failed for a long time and this could give user a caution that it probably not worth using it. Currently we are not using this to score the search ranking but probably it has potential to be in search scoring as well. I am not sure how much of effort it would take to bring execution timestamp in Redash, but just wanted to share that it might be worth it :)

>Dashboards do not have execution times or statuses in Redash.
Individual queries have a last refreshed concept, although I believe accessing this through the API requires actually fetching the most recent query results for each query.
There is no concept (that I'm aware of) of a successful vs. failed query (let alone dashboard) execution.
We are currently simply not populating the dashboard execution timestamps in Amundsen.

**Comment by jonhehir** [comment]
Thanks for the feedback, @jinhyukchang !

This is something we've discussed internally as well. We too have seen a lot of old and less valuable dashboards come through the search results, and some indicator of how recent and active the dashboard is would be very useful. We're unfortunately not populating execution times or view counts right now, but I do recognize that this information would be handy if used to rank dashboards appropriately.

**Comment by jonhehir** [comment]
Closing in favor of #543, #544, #545, #546, #547.
