### ISSUE TITLE
Feature Proposal: integrate Amundsen with tools that generate html reports ( popmon, pandas-profiling, great-expectations)

### ISSUE THREAD

**Issue by dechoma** [lyft/amundsen#525]
it would be great to be able to easily integrate Amundsen with tools that generate html reports, such as [popmon](https://github.com/ing-bank/popmon), [pandas-profiling]( https://github.com/pandas-profiling/pandas-profiling) or [great_expectations](https://github.com/great-expectations/great_expectations).
In short, the idea is to enable elastic way for linking tables to html reports describing data

## Expected Behavior or Use Case
 we should be able to add report resource metadata (report name, report url) to Atlas,Neo4j then the metadata can be linked to a table by meaning of a relation( one table can be linked to many reports )
If a table has an active relation to at least one report then in the table's detailed view, `Reports` button appears. User clicking on the button gets a drop-down list of related reports 

## Service or Ingestion ETL
involved services: metadata, frontend + common

## Possible Implementation
- add a new atlas entity type containing the report name and url and create relationship type to link it with Table 
- extend Table model in amundsen_common to include an optional report list field 
- modify the proxies to fill in the extended table model
- add dropdown report list in TableDetail view  

## Example Screenshots:

![Zrzut ekranu 2020-06-25 o 08 52 17](https://user-images.githubusercontent.com/29060284/85671997-bd0edd00-b6c2-11ea-89c7-5d009dc7b94b.png)
![Zrzut ekranu 2020-06-25 o 08 52 55](https://user-images.githubusercontent.com/29060284/85672014-c009cd80-b6c2-11ea-9f69-0695cbae48d3.png)
![Zrzut ekranu 2020-06-25 o 09 02 47](https://user-images.githubusercontent.com/29060284/85672029-c304be00-b6c2-11ea-9565-be76d083b7a6.png)

**Comment by feng-tao** [comment]
cc @ttannis Tamika, could you help to get some UX design inputs from our designer? I will take a look at the backend and also share internally .

**Comment by feng-tao** [comment]
hey @dechoma  @verdan @mgorsk1 I wonder whether the ING team has thought about showing data quality health score for dataset on Amundsen page as well?

**Comment by verdan** [comment]
@feng-tao yes, we are using programmatic_description for that purpose!

**Comment by mgorsk1** [comment]
@feng-tao after merging https://github.com/lyft/amundsencommon/pull/39 are we ok with bumping common version ?

**Comment by mgorsk1** [comment]
regarding the data quality health score it's been on our minds but I don't think it's done yet. the main reason is difficulty in coming up with single value that is relevant to every user (health might mean different things for different users). there is 5 star ranking standard in ING we might implement while doing a work on testing data quality with great expectations.

**Comment by mgorsk1** [comment]
I was wondering for the UI/UX part of the reports functionality that actually Amundsen has building blocks to make it very well-aligned. Namely - why not have another tab like Columns and Dashboards for it in a Table View ? It seems that it would be best aligned with current UI and open up possibilities like showing report generation date, description and type (the same every kind of table and dashboard have it's own icon).

WDYT @ttannis @feng-tao @verdan @dechoma 
![untitled (3)](https://user-images.githubusercontent.com/5680655/87117866-fbd39400-c279-11ea-9691-59fe6b4e4f70.png)

**Comment by dechoma** [comment]
@mgorsk1 on the one hand, the report is not an integral and obligatory part of the table like a columns, on the other hand, this approach is not as limited as dropdown and gives more possibilities, e.g. in the reports tab, measurements, from multiple reports could appear in one view. In general I think it's a very cool idea, I am curious what others think about it.

**Comment by verdan** [comment]
> I was wondering for the UI/UX part of the reports functionality that actually Amundsen has building blocks to make it very well-aligned. Namely - why not have another tab like Columns and Dashboards for it in a Table View ? It seems that it would be best aligned with current UI and open up possibilities like showing report generation date, description and type (the same every kind of table and dashboard have it's own icon).
> 
> WDYT @ttannis @feng-tao @verdan @dechoma ?
> ![untitled (3)](https://user-images.githubusercontent.com/5680655/87117866-fbd39400-c279-11ea-9691-59fe6b4e4f70.png)

The only issue I see from this approach is, that most of the times we don't have more than 2, 3 (or maybe 1) report(s), and creating a separate tab for one list item is a waste of real estate on the page, since we will be only having the links. (not something embedded HTMLs). I would still suggest to go for the dropdown.

**Comment by mgorsk1** [comment]
I guess for now we have ideas for 3 technologies for reports but If someone generated reports periodically and wanted to maintain historical entries then the number of reports could be greater than just 3.

**Comment by ttannis** [comment]
> > I was wondering for the UI/UX part of the reports functionality that actually Amundsen has building blocks to make it very well-aligned. Namely - why not have another tab like Columns and Dashboards for it in a Table View ? It seems that it would be best aligned with current UI and open up possibilities like showing report generation date, description and type (the same every kind of table and dashboard have it's own icon).
> > WDYT @ttannis @feng-tao @verdan @dechoma ?
> > ![untitled (3)](https://user-images.githubusercontent.com/5680655/87117866-fbd39400-c279-11ea-9691-59fe6b4e4f70.png)
> 
> The only issue I see from this approach is, that most of the times we don't have more than 2, 3 (or maybe 1) report(s), and creating a separate tab for one list item is a waste of real estate on the page, since we will be only having the links. (not something embedded HTMLs). I would still suggest to go for the dropdown.



> I was wondering for the UI/UX part of the reports functionality that actually Amundsen has building blocks to make it very well-aligned. Namely - why not have another tab like Columns and Dashboards for it in a Table View ? It seems that it would be best aligned with current UI and open up possibilities like showing report generation date, description and type (the same every kind of table and dashboard have it's own icon).
> 
> WDYT @ttannis @feng-tao @verdan @dechoma ?
> ![untitled (3)](https://user-images.githubusercontent.com/5680655/87117866-fbd39400-c279-11ea-9691-59fe6b4e4f70.png)

The current dropdown approach is preferred for now on our end. Due to what @verdan mentioned. 

The idea of someone wanting to maintain historical entries and potentially having many many reports is something I understand, but unless that is what you use case looks like today we should limit our choices to support your current use cases, and take an iterative approach.

**Comment by feng-tao** [comment]
+1 on @ttannis , I would prefer the dropdown as well.

**Comment by mgorsk1** [comment]
cool, thanks for prompt feedback! do you think then consider the current frontend implementation as a first iteration of the feature or are we still waiting for UX feedback ?

**Comment by ttannis** [comment]
> cool, thanks for prompt feedback! do you think then we can consider the current frontend implementation as a first iteration of the feature or are we still waiting for UX feedback ?

See feedback on PR: https://github.com/lyft/amundsenfrontendlibrary/pull/495#issuecomment-656292178

**Comment by feng-tao** [comment]
I believe the backend pr is still waiting for @verdan 's input.
