### ISSUE TITLE
Data ingestion in Amundsen and file formats supported

### ISSUE THREAD

**Issue by sarthak3097** [lyft/amundsen#533]
Does Amundsen only fetches metadata from the data sources?
Which all file formats does it support? (csv, parquet, json)

**Comment by feng-tao** [comment]
the ingestion doesn't limit to the file format as it only ingests the metadata. The file format could be csv/parquet/json or anything other formats.

**Comment by feng-tao** [comment]
feel free to reopen if it is not clear.

**Comment by sarthak3097** [comment]
Hi ,thank you for the quick response. I'll give an example to explain the situation. -
I have my data in a S3 bucket. So Amundsen would provide all the functionalities that include - crawling the complete data and ingesting only metadata into the Neo4j graph and that metadata will be used to build the catalog, right?

**Comment by sarthak3097** [comment]
Basically, Amundsen supports crawling of all the data sources as well (for creation of metadata which will be ingested)?
