### ISSUE TITLE
Feature Proposal: Make popularity number of users configurable 

### ISSUE THREAD

**Issue by jornh** [lyft/amundsen#534]
## Expected Behavior or Use Case

For the Neo4j proxy it's currently hardcoded to `> 10` here: https://github.com/lyft/amundsenmetadatalibrary/blob/v2.5.4/metadata_service/proxy/neo4j_proxy.py#L720 

That limit should be configurable, preferably in a common way across proxies available (Neo4j and Atlas) and planned (Neptune/JanusGraph).

## Service or Ingestion ETL

This relates to the metadata service.

## Possible Implementation

Simplest possible way is adding an environment variable like done elsewhere in the service and documenting its use.

## Context

That "popular" limit may depend on how big a company you have, or how thinly people are spread across different tables 😉 Would be a good idea to make it configurable.

Originated from this slack context: https://amundsenworkspace.slack.com/archives/CGFBVT23V/p1593635648003100?thread_ts=1593632245.001000&channel=CGFBVT23V&message_ts=1593635648.003100

**Comment by ttannis** [comment]
Can you explain the proposed implementation here as well/. I'm not understanding why we need any additional configurations in the frontend repository when the use case that needs configuring is related to the metadata service proxies.

**Comment by jacobhjkim** [comment]
@ttannis You are right. I didn't need to add any additional configurations in the frontend repository. I changed the PRs accordingly. PR `amundsenfrontendlibrary#502` is not related to this issue anymore.

**Comment by jornh** [comment]
Fixed by
