### ISSUE TITLE
What is best method to ingest metadata for S3 objects in Amundsen?

### ISSUE THREAD

**Issue by vikalpmullick** [lyft/amundsen#542]
### **Objective** : Ingest metadata for S3 objects (parquet/csv/json) in Amundsen.
- Amundsen provides connectors for AWS Athena and AWS Glue. I am able to ingest the s3 objects metadata using the athena connector.
- I used the "amundsendatabuilder/example/dags/athena_sample_dag.py" fot athena based ingestion.
- Athena tables were created using a Glue crawler.

I have the following queries:

1. Can Glue be independently used for ingesting the metadata from S3 ?
2. There is no example script for Glue based data ingestion. Please help me with sample code to connect to AWS Glue.
3. Also please let me know what is a better option?

**Comment by jornh** [comment]
1. I think it can (but haven't worked with Glue myself) 
2. Did you see the usage info at https://github.com/lyft/amundsendatabuilder#glueextractor? - if you combine that with one of the other samples, like Athena, you should be able to make it work. [Perhaps @PedroRossi, the original extractor contributor, do you have a quick sample to share?]
3. The one that works for your environment and fits with what else you already maintain. I don't think it's critical which metadata extractor is used, but which services in AWS people use differ, hence the abundance of options 😄

**Comment by PedroRossi** [comment]
1. Yes, but it is only intended to gather table metadata.
2. Just replace the configuration inside this function (https://github.com/lyft/amundsendatabuilder/blob/21a763add3c00c34b4f4c2d9809f59e50fb264c8/example/dags/athena_sample_dag.py#L77) as described in the GlueExtractor docs (link in the comment above).
3. I am only using this for Glue tables, but if you want to extract all s3 metadata you need another extractor to extract things that are not on Athena or Glue and maybe tables like csv files in a bucket.

**Comment by vikalpmullick** [comment]
@jornh @PedroRossi In the glue extractor what is "cluster_identifier_string"?

**Comment by vikalpmullick** [comment]
Thank You @jornh @PedroRossi , Using the Glue extractor in specified location worked for me.

**Comment by jornh** [comment]
@vikalpmullick great. Guess you can close this issue then.

**Comment by AdamMoffitt** [comment]
@vikalpmullick what were your steps to get the athena_sample_dag.py running? Am unable to run that airflow to populate the front end with data from athena.

**Comment by vikalpmullick** [comment]
@AdamMoffitt it should work if you provide connection details in L72-76 and aws AK/SK in L68,69. Pls share the error log if you still get any errors.
