### ISSUE TITLE
feature: Dashboard descriptions do not honor Markdown formatting

### ISSUE THREAD

**Issue by jonhehir** [lyft/amundsen#543]
## Expected Behavior

Markdown formatting in dashboard descriptions is rendered appropriately, just like for table descriptions.

## Current Behavior

These descriptions show up as plain-text.

## Screenshots

![image](https://user-images.githubusercontent.com/745011/87069422-26274200-c1e5-11ea-841a-0b939deb25a3.png)

## Your Environment

Most recent version of amundsenfrontendlibrary.

**Comment by ttannis** [comment]
Not a bug, just wasn't written that way intentionally because we didn't have a use case. :)
https://github.com/lyft/amundsenfrontendlibrary/pull/506

**Comment by ttannis** [comment]
Available on master, and will be included in the next frontend release.

**Comment by jonhehir** [comment]
Wow, very quick. Thank you!
