### ISSUE TITLE
bug: View Query link in dashboards references "Mode"

### ISSUE THREAD

**Issue by jonhehir** [lyft/amundsen#546]
The link to view a query for dashboards right now is hardcoded to say "View in Mode." This should render the appropriate dashboard product name.

## Screenshot

![image](https://user-images.githubusercontent.com/745011/87071433-37be1900-c1e8-11ea-9cee-99372d4acbe3.png)

## Your Environment

Most recent version of amundsenfrontendlibrary.

**Comment by feng-tao** [comment]
cc @ttannis @Golodhros 
I wonder whether we could get the dashboard product from backend. At the very least, we could rename the wording to be more generic.

**Comment by feng-tao** [comment]
the change is merged.
