### ISSUE TITLE
amundsendatabuilder -> hive_sample_dag is broken since HiveWatermark class is removed now 

### ISSUE THREAD

**Issue by pPanda-beta** [lyft/amundsen#550]
This sample sql is not gonna work anymore

https://github.com/lyft/amundsendatabuilder/blob/21a763add3c00c34b4f4c2d9809f59e50fb264c8/example/dags/hive_sample_dag.py#L65-L79

## Expected Behavior

ResultRows of the sql are mapped to Watermark models

## Current Behavior

It breaks since **compulsory constructor parameter 'database' of Watermark class is not provided**

## Possible Solution

Add a constant value column to sql query

```sql
SELECT from_unixtime(A0.CREATE_TIME) as create_time,
       'hive'                        as `database`, -- <<<<<<<<<<<<<<<<<< Solution
       C0.NAME                       as `schema`,
       B0.TBL_NAME                   as table_name,

```

## Steps to Reproduce
Just run the dag with your metastore db

## Your Environment

* Amundsen version used: 
dockerimages :
neo4j:3.3.0
elasticsearch:6.7.0
amundsendev/amundsen-search:2.4.0
amundsendev/amundsen-metadata:2.5.4
amundsendev/amundsen-frontend:2.1.1
Pypi:
**amundsen-databuilder==2.6.4**

* Data warehouse stores: hive metastore 2.3.7 on mysql by cloudsql

* Deployment (k8s or native): docker-compose
* Link to your fork or repository:

**Comment by feng-tao** [comment]
@pPanda-beta could you create a pr to fix the issue?
I think we just need to add `'hive' as `database`,` to the SQL (right before https://github.com/lyft/amundsendatabuilder/blob/21a763add3c00c34b4f4c2d9809f59e50fb264c8/example/dags/hive_sample_dag.py#L67 ).

**Comment by pPanda-beta** [comment]
@feng-tao 
Thats just one line below where I used 😆 ,
Sure no problem, I'll raise the PR.

**Comment by feng-tao** [comment]
thanks

**Comment by pPanda-beta** [comment]
@feng-tao -> Raised the PR : https://github.com/lyft/amundsendatabuilder/pull/305
