### ISSUE TITLE
SQL Statement in hive extractor has syntax issue.

### ISSUE THREAD

**Issue by sauravsahu02** [lyft/amundsen#573]
## Expected Behavior
Should be able to extract metadata from hive tables.

## Current Behavior
Getting error while compiling SQL statement provided in  hive_table_metadata_extractor.py
## Possible Solution
Correction of SQL_STATEMENT in hive_table_metadata_extractor.py

## Steps to Reproduce
1. To setup hive server using docker, I have followed the steps given in https://hub.docker.com/r/bde2020/hive/
2. Create new table inside hive, and then pass the connection_string and schema info as `hive://localhost:10000/default` to `example/dags/hive_sample_dag.py`
3. Run the dag script. 
4. Ensure the hive connection is working fine.
5. SQL_STATEMENT present in `hive_table_metadata_extractor.py` fails to compile.
ErrorMessage: `"Error while compiling statement : Failed ParseException line 3:5 cannot recognize input near '(' 'SELECT' 't' in joinSource"`

I am using latest version of amundsen and amundsendatabuilder.

**Comment by feng-tao** [comment]
@sauravsahu02  are you using postgres or mysql for hive metastore? We have been running this at lyft for 2 years now and haven't had much issues. Wonder whether this is related to the different db store.

**Comment by sauravsahu02** [comment]
Thanks for quick response.
I am using postgres. Which one are you using?
Have you made any change to the SQL_STATEMENT or at any other place?

**Comment by feng-tao** [comment]
The issue is the same as https://github.com/lyft/amundsen/issues/552 . We could make the SQL statement configurable to support postgres.
I could take a look and do a quick fix at the end of the week.

**Comment by saiharish97** [comment]
@feng-tao I am using MySQL as metastore , but it says syntax error. I am using Hive Version 2.3.4 and MySQL version "8.0.21 MySQL Community Server"

**Comment by sauravsahu02** [comment]
@feng-tao  Thanks for earlier response. Any latest update from your end for the fix?
