### ISSUE TITLE
bug: section.editable-section height does not expand in Chrome 84

### ISSUE THREAD

**Issue by jonhehir** [lyft/amundsen#575]
Is anyone else having this issue in Chrome? I'm seeing issues with long descriptions in Chrome 84 (on both macOS and Windows). See screenshots below.

## Possible Solution

Removing `display: flex` from `.left-panel` and removing `display: inline-table` from `.editable-section` seems to solve the problem.

## Steps to Reproduce

View a table or dashboard with a long description (or try to edit a table description). Anything that pushes the editable section beyond 70px should trigger this.

## Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/745011/88338905-16d8e600-cd07-11ea-934a-b1d4d23a3c4a.png)

![image](https://user-images.githubusercontent.com/745011/88338913-1b9d9a00-cd07-11ea-87b1-1f271f9712db.png)

## Context

This makes the sidebar unreadable in Chrome currently.

## Your Environment

Issue occurs using latest amundsenfrontend build on Chrome 84 in macOS and Windows. Firefox is not affected.

**Comment by feng-tao** [comment]
hey @jonhehir , glad that you raised this issue, we(Lyft) encounter the same issue as well. I tried the same fix which works but it has regression on other cases which the left panel no longer aligned.

cc @ttannis

**Comment by feng-tao** [comment]
@ttannis will do some more investigations to come up with a fix.

**Comment by jonhehir** [comment]
Yeah, I wasn't sure of the best fix here, which is why I opted to open an issue rather than a PR. Would definitely appreciate a fix, though. 😄

**Comment by feng-tao** [comment]
https://coryrylan.com/blog/css-gap-space-with-flexbox and https://usefulangle.com/web-updates/post/83/chrome-84-released seems to be related.
