### ISSUE TITLE
Initiating amundsen on Red Hat 7 Hangs during startup

### ISSUE THREAD

**Issue by deyerly** [lyft/amundsen#577]
Unable to get Amundsen to properly startup using "Quick Start" / Bootstrap. Provided log of startup during execution of step #3 "Enter cloned directory and run". 

## Expected Behavior
Amundsen should be running under docker. Executing: docker_compose -f docker-Amundsen.yml up 

## Current Behavior
Start up hangs

## Possible Solution
Unknown.

## Steps to Reproduce
execute: docker_compose -f docker-Amundsen.yml up under sudo

## Context
Unable to install on server (Red Hat 7) platform to evaluate and determine if tool would be good fit for our organization to leverage for Glossary. 

## Your Environment
OS Red Hat 7 
Amunsen version used: See attachment. 
Neo4j as data store

**Comment by jornh** [comment]
Doc was updated to clarify as per https://github.com/lyft/amundsen/pull/587#issuecomment-666656619

This issue can be closed @deyerly @feng-tao

**Comment by feng-tao** [comment]
thanks @jornh !
