### ISSUE TITLE
Move the databuilder to py3, document warning when using the usage extractor 

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#58]
We should document the repo to let users know that if they want to use python3 , the usage extractor won't work.

**Comment by jornh** [comment]
@feng-tao with https://github.com/lyft/amundsendatabuilder/pull/140 merged what else is needed before this can be closed? (#40 is still there to track antlr update to py3)

**Comment by feng-tao** [comment]
@jornh I think we could close this issue now. Thanks for checking.
