### ISSUE TITLE
Substring search from Amundsen UI

### ISSUE THREAD

**Issue by sauravsahu02** [lyft/amundsen#600]
## Expected Behavior or Use Case
I should be able to search or list the table on Amundsen UI by typing sub-string of table metadata like table name, column name, table description, tags, etc.  
If I have a  table '**customer**', I should be able to list the table by typing its substring e.g. "**cust**" or "**custo**".

**Comment by jornh** [comment]
AFAIK it's a deliberate choice in the basic search on the frontpage/top banner to only return exact matches. 

If you want what you describe it can be accomplished by clicking into advanced search and entering e.g `cust*` or `custo*` with a wildcard  into for example the table name field - see under point 8 in https://lyft.github.io/amundsen/installation/#bootstrap-a-default-version-of-amundsen-using-docker for a picture of the UI.
