### ISSUE TITLE
Add sample presto view data for quick start

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#61]
@youngyjd provides a presto view extractor in https://github.com/lyft/amundsendatabuilder/pull/25/files. We should provide sample presto view data for quick start documentation.

**Comment by jornh** [comment]
@feng-tao, the Quickstart now has a view, even though it’s just feed from the CSVs: https://github.com/lyft/amundsendatabuilder/blob/v2.1.0/example/sample_data/sample_col.csv#L11 and https://github.com/lyft/amundsendatabuilder/blob/v2.1.0/example/sample_data/sample_table.csv#L4 which also sets the `is_view` flag.

Does this resolve this issue or do you want something more specific?

**Comment by feng-tao** [comment]
I am the issue could be closed now.

**Comment by rqmulti** [comment]
i dont know if is it important but could be nice for the comunity samples of dags and script implementing the extractors.
