### ISSUE TITLE
Add sample high/low watermark data to quick start

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#62]
We use 
```        
SELECT From_unixtime(A0.create_time) as create_time,
               C0.NAME as schema_name,
               B0.tbl_name as table_name,
               {func}(A0.part_name) as part_name,
               {watermark} as part_type
        FROM   PARTITIONS A0
               LEFT OUTER JOIN TBLS B0
                            ON A0.tbl_id = B0.tbl_id
               LEFT OUTER JOIN DBS C0
                            ON B0.db_id = C0.db_id
        WHERE  C0.NAME IN {schemas}
               AND B0.tbl_type IN ( 'EXTERNAL_TABLE', 'MANAGED_TABLE' )
               AND A0.PART_NAME NOT LIKE '%%__HIVE_DEFAULT_PARTITION__%%'
        GROUP  BY C0.NAME, B0.tbl_name
        ORDER by create_time desc
```

as the high metastore query to get the high watermark and low watermark for a hive table. And we have already included the datamodel in https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/models/hive_watermark.py .

We should be able to provide a sample data with csv format to quick start. UI has already had support with watermark data.

**Comment by Mikhail-Ivanov** [comment]
I'd like to take this one if you don't mind

**Comment by feng-tao** [comment]
@Mikhail-Ivanov all yours :)

**Comment by Mikhail-Ivanov** [comment]
Related PR:
https://github.com/lyft/amundsendatabuilder/pull/145

**Comment by jornh** [comment]
@Mikhail-Ivanov and @feng-tao anything else needed to close this with https://github.com/lyft/amundsendatabuilder/pull/145 merged?

**Comment by feng-tao** [comment]
yeap
