### ISSUE TITLE
Add sample data for hive table last updated timestamp

### ISSUE THREAD

**Issue by feng-tao** [lyft/amundsen#63]
We had the last update timestamp extractor in https://github.com/lyft/amundsendatabuilder/blob/master/databuilder/extractor/hive_table_last_updated_extractor.py.

This issue is to provide a quick start sample data to show hive table last updated timestamp.

**Comment by samshuster** [comment]
pull request: https://github.com/lyft/amundsendatabuilder/pull/152

**Comment by feng-tao** [comment]
nice, thanks
