### ISSUE TITLE
adding tags in front end does not update the elastic indexes

### ISSUE THREAD

**Issue by siddharthgarishakurthi** [lyft/amundsen#81]
When updating "Tags" from frontend, it does update backend Neo4j but does not update Elastic indexes. Hence, once tags are updated, they are not searchable.

**Comment by jornh** [comment]
Duplicate of https://github.com/lyft/amundsen/issues/52

I’d say a PR towards ticking the last box after search service API would be most welcome.

**Comment by ttannis** [comment]
Closing as this is a duplicate. Please follow #52, and you are welcome to assist us in implementing it!
