### ISSUE TITLE
improve table description formatting

### ISSUE THREAD

**Issue by javamonkey79** [lyft/amundsen#98]
Currently, the table description strips out line breaks and is string only.

It would be much better, if it supported html, or markdown instead.

**Comment by Mikhail-Ivanov** [comment]
Associated PRs:
https://github.com/lyft/amundsenmetadatalibrary/pull/79
https://github.com/lyft/amundsenfrontendlibrary/pull/298

**Comment by javamonkey79** [comment]
@feng-tao I think this is now done, now that both prs are merged. Do you want to keep it open still?

**Comment by feng-tao** [comment]
yeap, thanks @javamonkey79!
